<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
<meta name="GENERATOR" content="TtH 3.80">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
 <style type="text/css"> div.p { margin-top: 7pt;}</style>
 <style type="text/css"><!--
 td div.comp { margin-top: -0.6ex; margin-bottom: -1ex;}
 td div.comb { margin-top: -0.6ex; margin-bottom: -.6ex;}
 td div.hrcomp { line-height: 0.9; margin-top: -0.8ex; margin-bottom: -1ex;}
 td div.norm {line-height:normal;}
 span.roman {font-family: serif; font-style: normal; font-weight: normal;} 
 span.overacc2 {position: relative;  left: .8em; top: -1.2ex;}
 span.overacc1 {position: relative;  left: .6em; top: -1.2ex;} --></style>
<title>Try-catch statement</title>
</head>

<body>
 <h2><a name="tth_sEc14">
14</a>&nbsp;&nbsp;Try-catch statement</h2>

<div class="p"><!----></div>
Statement ::= TryStatement <br />
TryStatement ::= <b>try</b> BlockStatement Catch  <br />
             &#124; <b>try</b> BlockStatement Catch Finally <br />
Catch ::= <b>catch</b> <b>(</b> Formal <b>)</b> BlockStatement <br />
Finally ::= <b>finally</b> BlockStatement <br />


<div class="p"><!----></div>
Exceptions are handled with a <b>try</b> statement.
A <b>try</b> statement consists of a <b>try</b> block, zero or more
<b>catch</b> blocks, and an optional <b>finally</b> block.

<div class="p"><!----></div>
First, the <b>try</b> block is evaluated.  If the block throws an
exception, control transfers to the first matching <b>catch</b>
block, if any.  A <b>catch</b> matches if the value of the
exception thrown is a subclass of the <b>catch</b> block's formal
parameter type.

<div class="p"><!----></div>
The <b>finally</b> block, if present, is evaluated on all normal
and exceptional control-flow paths from the <b>try</b> block.
If the <b>try</b> block completes normally
or via a <b>return</b>, a <b>break</b>, or a
<b>continue</b> statement, 
the <b>finally</b>
block is evaluated, and then control resumes at
the statement following the <b>try</b> statement, at the branch target, or at
the caller as appropriate.
If the <b>try</b> block completes
exceptionally, the <b>finally</b> block is evaluated after the
matching <b>catch</b> block, if any, and then the
exception is rethrown.

<div class="p"><!----></div>
It is a static error to attempt to catch an exception type which is not
throwable by the block.  

<div class="p"><!----></div>

</body>
</html>